/* Verilog netlist generated by SCUBA Diamond_2.2_Production (99) */
/* Module Version: 5.4 */
/* D:\Programs\Diamond\diamond\2.2_x64\ispfpga\bin\nt64\scuba.exe -w -n ddr -lang verilog -synth synplify -bus_exp 7 -bb -arch xo2c00 -type iol -mode out -io_type LVCMOS25 -width 1 -freq_in 75 -gear 1 -clk sclk -del -1 -e  */
/* Tue Nov 10 14:55:39 2015 */


`timescale 1 ns / 1 ps
module ddr (clkop, clkos, clkout, reset, sclk, dataout, dout)/* synthesis syn_noprune=1 *//* synthesis NGD_DRC_MASK=1 */;// exemplar attribute ddr dont_touch true 
    input wire clkop;
    input wire clkos;
    input wire reset;
    input wire [1:0] dataout;
    output wire clkout;
    output wire sclk;
    output wire [0:0] dout;

    wire db0;
    wire da0;
    wire buf_clkout;
    wire scuba_vlo;
    wire scuba_vhi;
    wire buf_douto0;

    OB Inst4_OB (.I(buf_clkout), .O(clkout))
             /* synthesis IO_TYPE="LVCMOS25" */;

    ODDRXE Inst3_ODDRXE0 (.D0(da0), .D1(db0), .SCLK(clkop), .RST(reset), 
        .Q(buf_douto0));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    ODDRXE Inst2_ODDRXE (.D0(scuba_vhi), .D1(scuba_vlo), .SCLK(clkos), .RST(reset), 
        .Q(buf_clkout));

    OB Inst1_OB0 (.I(buf_douto0), .O(dout[0]))
             /* synthesis IO_TYPE="LVCMOS25" */;

    assign sclk = clkop;
    assign db0 = dataout[1];
    assign da0 = dataout[0];


    // exemplar begin
    // exemplar attribute Inst4_OB IO_TYPE LVCMOS25
    // exemplar attribute Inst1_OB0 IO_TYPE LVCMOS25
    // exemplar end

endmodule
